// Mocks generated by Mockito 5.4.6 from annotations
// in demo_ncl/test/unit/admin_features_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i13;

import 'package:demo_ncl/models/audit_log_model.dart' as _i12;
import 'package:demo_ncl/models/b2b_lead_model.dart' as _i9;
import 'package:demo_ncl/models/logistics_model.dart' as _i10;
import 'package:demo_ncl/models/payroll_model.dart' as _i5;
import 'package:demo_ncl/models/quality_flag_model.dart' as _i8;
import 'package:demo_ncl/models/temp_card_model.dart' as _i3;
import 'package:demo_ncl/models/time_record_model.dart' as _i4;
import 'package:demo_ncl/providers/admin_provider.dart' as _i7;
import 'package:logging/logging.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeLogger_0 extends _i1.SmartFake implements _i2.Logger {
  _FakeLogger_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTempCard_1 extends _i1.SmartFake implements _i3.TempCard {
  _FakeTempCard_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTimeRecord_2 extends _i1.SmartFake implements _i4.TimeRecord {
  _FakeTimeRecord_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePayrollReport_3 extends _i1.SmartFake implements _i5.PayrollReport {
  _FakePayrollReport_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFuture_4<T1> extends _i1.SmartFake implements _i6.Future<T1> {
  _FakeFuture_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AdminProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdminProvider extends _i1.Mock implements _i7.AdminProvider {
  MockAdminProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isDisposed => (super.noSuchMethod(
        Invocation.getter(#isDisposed),
        returnValue: false,
      ) as bool);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  _i6.Stream<List<_i7.AdminUser>> get usersStream => (super.noSuchMethod(
        Invocation.getter(#usersStream),
        returnValue: _i6.Stream<List<_i7.AdminUser>>.empty(),
      ) as _i6.Stream<List<_i7.AdminUser>>);

  @override
  _i6.Stream<List<_i7.AdminBooking>> get bookingsStream => (super.noSuchMethod(
        Invocation.getter(#bookingsStream),
        returnValue: _i6.Stream<List<_i7.AdminBooking>>.empty(),
      ) as _i6.Stream<List<_i7.AdminBooking>>);

  @override
  List<_i7.AdminActivity> get recentActivities => (super.noSuchMethod(
        Invocation.getter(#recentActivities),
        returnValue: <_i7.AdminActivity>[],
      ) as List<_i7.AdminActivity>);

  @override
  _i6.Stream<List<_i3.TempCard>> get tempCardsStream => (super.noSuchMethod(
        Invocation.getter(#tempCardsStream),
        returnValue: _i6.Stream<List<_i3.TempCard>>.empty(),
      ) as _i6.Stream<List<_i3.TempCard>>);

  @override
  _i6.Stream<List<_i4.TimeRecord>> get proxyRecordsStream =>
      (super.noSuchMethod(
        Invocation.getter(#proxyRecordsStream),
        returnValue: _i6.Stream<List<_i4.TimeRecord>>.empty(),
      ) as _i6.Stream<List<_i4.TimeRecord>>);

  @override
  _i6.Stream<List<String>> get blockedStaffStream => (super.noSuchMethod(
        Invocation.getter(#blockedStaffStream),
        returnValue: _i6.Stream<List<String>>.empty(),
      ) as _i6.Stream<List<String>>);

  @override
  _i6.Stream<List<_i8.QualityFlag>> get qualityFlagsStream =>
      (super.noSuchMethod(
        Invocation.getter(#qualityFlagsStream),
        returnValue: _i6.Stream<List<_i8.QualityFlag>>.empty(),
      ) as _i6.Stream<List<_i8.QualityFlag>>);

  @override
  _i6.Stream<List<_i9.B2BLead>> get leadsStream => (super.noSuchMethod(
        Invocation.getter(#leadsStream),
        returnValue: _i6.Stream<List<_i9.B2BLead>>.empty(),
      ) as _i6.Stream<List<_i9.B2BLead>>);

  @override
  _i6.Stream<List<_i10.LogisticsEvent>> get logisticsStream =>
      (super.noSuchMethod(
        Invocation.getter(#logisticsStream),
        returnValue: _i6.Stream<List<_i10.LogisticsEvent>>.empty(),
      ) as _i6.Stream<List<_i10.LogisticsEvent>>);

  @override
  _i6.Stream<List<_i5.PayrollReport>> get payrollReportsStream =>
      (super.noSuchMethod(
        Invocation.getter(#payrollReportsStream),
        returnValue: _i6.Stream<List<_i5.PayrollReport>>.empty(),
      ) as _i6.Stream<List<_i5.PayrollReport>>);

  @override
  _i2.Logger get logger => (super.noSuchMethod(
        Invocation.getter(#logger),
        returnValue: _FakeLogger_0(
          this,
          Invocation.getter(#logger),
        ),
      ) as _i2.Logger);

  @override
  bool get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: false,
      ) as bool);

  @override
  bool get hasError => (super.noSuchMethod(
        Invocation.getter(#hasError),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void setLoading(bool? loading) => super.noSuchMethod(
        Invocation.method(
          #setLoading,
          [loading],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> refreshData() => (super.noSuchMethod(
        Invocation.method(
          #refreshData,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> loadMoreUsers({bool? reset = false}) => (super.noSuchMethod(
        Invocation.method(
          #loadMoreUsers,
          [],
          {#reset: reset},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> loadMoreBookings({bool? reset = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadMoreBookings,
          [],
          {#reset: reset},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateUserStatus(
    String? userId,
    bool? isBanned,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserStatus,
          [
            userId,
            isBanned,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateBookingStatus(
    String? bookingId,
    String? newStatus,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBookingStatus,
          [
            bookingId,
            newStatus,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> batchUpdateUsersStatus(
    List<String>? userIds,
    bool? isBanned,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchUpdateUsersStatus,
          [
            userIds,
            isBanned,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Stream<Map<String, dynamic>> getStatistics() => (super.noSuchMethod(
        Invocation.method(
          #getStatistics,
          [],
        ),
        returnValue: _i6.Stream<Map<String, dynamic>>.empty(),
      ) as _i6.Stream<Map<String, dynamic>>);

  @override
  _i6.Stream<List<_i7.AdminUser>> searchUsers(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchUsers,
          [query],
        ),
        returnValue: _i6.Stream<List<_i7.AdminUser>>.empty(),
      ) as _i6.Stream<List<_i7.AdminUser>>);

  @override
  _i6.Stream<List<_i7.AdminBooking>> searchBookings(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchBookings,
          [query],
        ),
        returnValue: _i6.Stream<List<_i7.AdminBooking>>.empty(),
      ) as _i6.Stream<List<_i7.AdminBooking>>);

  @override
  String generateTempCardCode() => (super.noSuchMethod(
        Invocation.method(
          #generateTempCardCode,
          [],
        ),
        returnValue: _i11.dummyValue<String>(
          this,
          Invocation.method(
            #generateTempCardCode,
            [],
          ),
        ),
      ) as String);

  @override
  _i6.Future<_i3.TempCard> issueTempCard({
    required String? staffId,
    required String? staffName,
    String? notes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #issueTempCard,
          [],
          {
            #staffId: staffId,
            #staffName: staffName,
            #notes: notes,
          },
        ),
        returnValue: _i6.Future<_i3.TempCard>.value(_FakeTempCard_1(
          this,
          Invocation.method(
            #issueTempCard,
            [],
            {
              #staffId: staffId,
              #staffName: staffName,
              #notes: notes,
            },
          ),
        )),
      ) as _i6.Future<_i3.TempCard>);

  @override
  _i6.Future<_i3.TempCard?> validateTempCard(String? code) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateTempCard,
          [code],
        ),
        returnValue: _i6.Future<_i3.TempCard?>.value(),
      ) as _i6.Future<_i3.TempCard?>);

  @override
  _i6.Future<void> deactivateTempCard(
    String? cardId,
    String? reason,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deactivateTempCard,
          [
            cardId,
            reason,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i4.TimeRecord> createProxyTimeRecord({
    required String? staffId,
    required String? staffName,
    required String? jobId,
    required String? jobName,
    required DateTime? checkInTime,
    DateTime? checkOutTime,
    String? notes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createProxyTimeRecord,
          [],
          {
            #staffId: staffId,
            #staffName: staffName,
            #jobId: jobId,
            #jobName: jobName,
            #checkInTime: checkInTime,
            #checkOutTime: checkOutTime,
            #notes: notes,
          },
        ),
        returnValue: _i6.Future<_i4.TimeRecord>.value(_FakeTimeRecord_2(
          this,
          Invocation.method(
            #createProxyTimeRecord,
            [],
            {
              #staffId: staffId,
              #staffName: staffName,
              #jobId: jobId,
              #jobName: jobName,
              #checkInTime: checkInTime,
              #checkOutTime: checkOutTime,
              #notes: notes,
            },
          ),
        )),
      ) as _i6.Future<_i4.TimeRecord>);

  @override
  _i6.Future<bool> areHoursInPayroll(String? recordId) => (super.noSuchMethod(
        Invocation.method(
          #areHoursInPayroll,
          [recordId],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<void> approveProxyHours({
    required String? recordId,
    required bool? approved,
    String? adminNotes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #approveProxyHours,
          [],
          {
            #recordId: recordId,
            #approved: approved,
            #adminNotes: adminNotes,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> blockStaffInterface(
    String? staffId,
    String? reason,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #blockStaffInterface,
          [
            staffId,
            reason,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> unblockStaffInterface(String? staffId) =>
      (super.noSuchMethod(
        Invocation.method(
          #unblockStaffInterface,
          [staffId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<bool> isStaffBlocked(String? staffId) => (super.noSuchMethod(
        Invocation.method(
          #isStaffBlocked,
          [staffId],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<void> flagQualityIssue({
    required String? jobId,
    required String? jobName,
    required String? staffId,
    required String? staffName,
    required String? issueType,
    required String? description,
    int? severity = 1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #flagQualityIssue,
          [],
          {
            #jobId: jobId,
            #jobName: jobName,
            #staffId: staffId,
            #staffName: staffName,
            #issueType: issueType,
            #description: description,
            #severity: severity,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> resolveQualityFlag(
    String? flagId,
    String? resolution,
    String? resolvedBy,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #resolveQualityFlag,
          [
            flagId,
            resolution,
            resolvedBy,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> addB2BLead({
    required String? companyName,
    required String? contactName,
    required String? email,
    required String? phone,
    required String? serviceInterest,
    String? notes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addB2BLead,
          [],
          {
            #companyName: companyName,
            #contactName: contactName,
            #email: email,
            #phone: phone,
            #serviceInterest: serviceInterest,
            #notes: notes,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateLeadStatus(
    String? leadId,
    _i9.LeadStatus? status,
    String? notes,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateLeadStatus,
          [
            leadId,
            status,
            notes,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> logLogisticsEvent({
    required String? staffId,
    required String? jobId,
    required String? eventType,
    required String? description,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #logLogisticsEvent,
          [],
          {
            #staffId: staffId,
            #jobId: jobId,
            #eventType: eventType,
            #description: description,
            #metadata: metadata,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Stream<List<_i10.LogisticsEvent>> getJobLogistics(String? jobId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getJobLogistics,
          [jobId],
        ),
        returnValue: _i6.Stream<List<_i10.LogisticsEvent>>.empty(),
      ) as _i6.Stream<List<_i10.LogisticsEvent>>);

  @override
  _i6.Future<_i5.PayrollReport> generateDraftPayroll({
    required DateTime? startDate,
    required DateTime? endDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateDraftPayroll,
          [],
          {
            #startDate: startDate,
            #endDate: endDate,
          },
        ),
        returnValue: _i6.Future<_i5.PayrollReport>.value(_FakePayrollReport_3(
          this,
          Invocation.method(
            #generateDraftPayroll,
            [],
            {
              #startDate: startDate,
              #endDate: endDate,
            },
          ),
        )),
      ) as _i6.Future<_i5.PayrollReport>);

  @override
  _i6.Future<void> finalizePayroll(String? reportId) => (super.noSuchMethod(
        Invocation.method(
          #finalizePayroll,
          [reportId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Stream<List<_i12.AuditLog>> getAuditLogs(String? targetId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAuditLogs,
          [targetId],
        ),
        returnValue: _i6.Stream<List<_i12.AuditLog>>.empty(),
      ) as _i6.Stream<List<_i12.AuditLog>>);

  @override
  void setError(
    String? error, {
    bool? notify = true,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #setError,
          [error],
          {#notify: notify},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<T> withRetry<T>(
    _i6.Future<T> Function()? operation, {
    String? cacheKey,
    Duration? cacheDuration,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #withRetry,
          [operation],
          {
            #cacheKey: cacheKey,
            #cacheDuration: cacheDuration,
          },
        ),
        returnValue: _i11.ifNotNull(
              _i11.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #withRetry,
                  [operation],
                  {
                    #cacheKey: cacheKey,
                    #cacheDuration: cacheDuration,
                  },
                ),
              ),
              (T v) => _i6.Future<T>.value(v),
            ) ??
            _FakeFuture_4<T>(
              this,
              Invocation.method(
                #withRetry,
                [operation],
                {
                  #cacheKey: cacheKey,
                  #cacheDuration: cacheDuration,
                },
              ),
            ),
      ) as _i6.Future<T>);

  @override
  void debounce(
    Duration? duration,
    _i13.VoidCallback? callback,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #debounce,
          [
            duration,
            callback,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> handleError(
    dynamic error, {
    StackTrace? stackTrace,
    bool? notify = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #handleError,
          [error],
          {
            #stackTrace: stackTrace,
            #notify: notify,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void setupConnectivityListener() => super.noSuchMethod(
        Invocation.method(
          #setupConnectivityListener,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
